name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        #with:
          #source-url: https://nuget.pkg.github.com/<organization>/index.json
        #env:
          #NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Nuget pack
        run: |
          export version="0.1.$((${{github.run_number}}-2))"
          echo $version
      
      - name: Build and generate MixinSourceGenerator package
        run: |
          echo "version="+$version
          dotnet pack Generator/MixinSourceGenerator.csproj -c Release -p:PackageVersion=$version -o out
